apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dummy
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ramiroduarteavalos/argocd.git
        revision: HEAD
        files:
          - path: "argocd/dummy/config/dev-qa/*"
  template:
    metadata:
      name: "{{project}}-{{environment}}"
    spec:
      project: "{{project}}-{{environment}}"
      source:
        path: "argocd/dummy"
        repoURL: https://github.com/ramiroduarteavalos/argocd.git
        targetRevision: main
        helm:
          releaseName: "{{project}}"
          valueFiles:
            - "argocd/dummy/values.{{environment}}.yaml"
      destination:
        name: "{{cluster}}"
        namespace: "{{project}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true