apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sarlanga.fullname" . }}
  labels:
    {{- include "sarlanga.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
{{- end}}
