apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sarlanga.fullname" . }}-secrets  
  labels:
    {{- include "sarlanga.labels" . | nindent 4 }} 
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
{{- range $key, $val := .Values.Secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
