name: dummy

product: demo

imageTag: v1.0.3

command:
  - sh
  - -c
  - ls -l

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10

resources:
  limits:
    cpu: 600m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 256Mi

